# Generated by Django 3.2.12 on 2023-03-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True #Indicates this entity should be the first executed in the application

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
